[package]
name = "zero-deeplearning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray="0.15.6"
plotters = "0.3.3"
mnist = "0.6.0"